#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <fhelper.h>
#include <monte_carlo.h>

#define L		128
#define FORCE_SEED  0

#define DETA        1e-2
#define TMAX        1e6
#define TMIN        1
#define TTICS       30


#define DETAMAX     1
#define DETAMIN     1e-5

#define SCALE       1 // 0 -> LINEAR
                      // 1 -> LOG
#define MODE        0 // 0 -> temporal
                      // 1 -> correlation time
void simulate(void);
void setup(void);
void mergeTemporaryValues(void);
int onTimeSimulate(float);
void writeSpecifications(void);


void takeMeasures(float);
void onParticleUpdate(int);


FILE *f;
unsigned int seed;
int xA, xB, xM, tempXA, tempXB, tempXM;
double dEta = DETA;
float etaA, etaB, tempEtaA, tempEtaB, timeT, lastMeasure = 0;


int main() {
    seed = setupRandom(FORCE_SEED ? 123456789 : 0);

    char name[50];
    sprintf(name, "data_W_L%d", L);
    f = safeSeedOpen(name, ".dat", &seed, 0);
    writeSpecifications();
    simulate();
    fclose(f);
    
	return 0;
}

void simulate(void){
    setup();
    float *t_arr = smalloc(TTICS * sizeof(float));
    if(SCALE){
        geomProgression(t_arr, TMIN, TMAX, TTICS);
    } else {
        linearProgression(t_arr, TMIN, TMAX, TTICS);
    }
    float nextTime;
    for(int i = 0; i < TTICS; i++){
        nextTime = t_arr[i];
        while(onTimeSimulate(nextTime)){}
    }
}

void dEtaEvolution(void){
    float *dEta_arr = smalloc(TTICS * sizeof(float));
    if(SCALE){
        geomProgression(dEta_arr, DETAMIN, DETAMAX, TTICS);
    } else {
        linearProgression(dEta_arr, DETAMIN, DETAMAX, TTICS);
    }
    for(int i = 0; i < TTICS; i++){
        dEta = dEta_arr[i];
        setup();
        while(onTimeSimulate(TMAX)){}
    
    }

}
void setup(){
    xA = (int)(-L / 2);
    xB = (int)( L / 2);
    xM = 0;
    etaA = 0.0;
    etaB = 0.0;
    timeT = 0.0;
    tempXA = xA;
    tempXB = xB;
    tempXM = xM;
    tempEtaA = etaA;
    tempEtaB = etaB;
}

void mergeTemporaryValues(){
    xA = tempXA;
    xB = tempXB;
    xM = tempXM;
    etaA = tempEtaA;
    etaB = tempEtaB;
}

int onTimeSimulate(float timeTarget) {
    
    if(timeT >= timeTarget){
        takeMeasures(timeTarget);
        return 0;
    }
    mergeTemporaryValues();
	timeT += 1.0 / 3.0;
	onParticleUpdate(randomIntOf(0, 3));
    return 1;
}

void writeSpecifications(void){
    fprintf(f, "# Inertial Walls on Random Walk\n");
	fprintf(f, "# Data generated by: L. Possamai\n");
	fprintf(f, "# Seed: %d\n", seed);
	if(SCALE == 0){
		fprintf(f, "# Linear Measures: %d\n", TTICS);
	} else {
		fprintf(f, "# Log Measures: %d\n", TTICS);
	}
	switch(MODE){
	    case 0:
	        fprintf(f, "# t, xA, xB, xM, W\n");
	        break;
	    case 1:
	        fprintf(f, "# t, W(0)W(t), W, W2\n");
	        break;        
	}
    
}

void takeMeasures(float timeTarget){
    if(MODE == 0){
        
        fprintf(f, "%.2f %d %d %d %d\n", timeTarget, xA, xB, xM, xB - xA);
    } else if(MODE == 1){
        if(timeTarget == TMIN){
            lastMeasure = xB - xA;
        }

        fprintf(f, "%.2f %d %d %d\n", timeTarget, (int)lastMeasure * (xA - xB), xB - xA, (xB - xA) * (xB - xA));
        
    }
    
}
//0 = A, 1 = M, 2 = B;
void onParticleUpdate(int particle){
    
    switch(particle){
        case 1:
            tempXM += randomIntOf(-1, 2);
            if(tempXM == tempXA) {
                tempXA--;
                tempEtaA = 0; 
            }
            if(tempXM == tempXB) {
                tempXB++;
                tempEtaB = 0;
            }
            break;
        case 0:
            etaA += dEta;
            if(etaA >= 1.0){
                etaA = 0;
                tempXA++;
                if(tempXA == tempXM){
                    tempXM++;
                }
            }
            break;
        case 2:
            etaB += dEta;
            if(etaB >= 1.0){
                etaB = 0;
                tempXB--;
                if(tempXB == tempXM){
                    tempXM--;
                }
            }
            break;
        
    }
    
}








