#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <fhelper.h>
#include <monte_carlo.h>

#define FORCE_SEED  0

//  Temporal Evolution   #
#define DETA        1e-2
#define TMAX        1e7
#define TMIN        1
//  Non temporal Evolution
#define TTICS       60
#define LOOPS       1e5

// For dEta Evolution
#define DETAMAX     1e-2
#define DETAMIN     1e-3

// Evolution Parameter Scale
#define SCALE       1 // 0 -> LINEAR
                      // 1 -> LOG
#define COLLISION_RESET 0
// Mode
#define MODE        0 // 0 -> temporal
                      // 1 -> w(deta)
void simulate(void);
void setup(void);
void setupFile(char*, int);
void mergeTemporaryValues(void);
int onTimeSimulate(float);
void writeSpecifications(FILE*);
void dEtaEvolution(void);
float timeForDEta(float, int);
void takeMeasures(float);
void onParticleUpdate(int);



FILE *f, *fCompl;
unsigned int seed;
int xA, xB, xM, tempXA, tempXB, tempXM, W0 = 2;
float dEta = DETA;
double timeT;
float etaA, etaB, lastMeasure = 0;


int main() {
    seed = setupRandom(FORCE_SEED ? 123456789 : 0);

    if(MODE == 0){
        setupFile("data_rwmw_W", 0);
        simulate();
        fclose(f);

    } else if(MODE == 1){
        setupFile("data_rwmw_MEAN_w", 1);
        dEtaEvolution();
        fclose(fCompl);    
    }
    
    
	return 0;
}

void setupFile(char* name, int isCompl){
    if(isCompl){
        fCompl = safeSeedOpen(name, ".dat", &seed, 0);
        writeSpecifications(fCompl);
        return;
    }
    f = safeSeedOpen(name, ".dat", &seed, 0);
    writeSpecifications(f);
}

void simulate(void){
    setup();
    float *t_arr = smalloc(TTICS * sizeof(float));
    if(SCALE){
        geomProgression(t_arr, (int)TMIN, (int)TMAX, TTICS);
    } else {
        linearProgression(t_arr, (int)TMIN, (int)TMAX, TTICS);
    }
    float nextTime;
    for(int i = 0; i < TTICS; i++){
        nextTime = t_arr[i];
        while(onTimeSimulate(nextTime)){}
    }
    free(t_arr);
}

void dEtaEvolution(void){
    float *dEta_arr = smalloc(TTICS * sizeof(float));
    if(SCALE){
        geomProgression(dEta_arr, DETAMIN, DETAMAX, TTICS);
    } else {
        linearProgression(dEta_arr, DETAMIN, DETAMAX, TTICS);
    }
    for(int i = 0; i < TTICS; i++){
        dEta = dEta_arr[i];
        char name[50] = "";
        sprintf(name, "data_rwmw_w_dEtae%.5f", dEta);
        setupFile(name, 0);
        lastMeasure = 0;
        setup();
        float t_stat = timeForDEta(dEta, 1);
        while(onTimeSimulate(t_stat)){}
        
        for(int i = 0; i < LOOPS; i++){
            t_stat += timeForDEta(dEta, 0);
            while(onTimeSimulate(t_stat)){}
        }
        fprintf(fCompl, "%.5f %.2f\n", dEta, lastMeasure / (float) LOOPS);
        fclose(f);
    
    }
    free(dEta_arr);

}


void setup(){
    xA = (int)(-W0 / 2);
    xB = (int)( W0 / 2);
    xM = 0;
    etaA = 0.0;
    etaB = 0.0;
    timeT = 0.0;
    tempXA = xA;
    tempXB = xB;
    tempXM = xM;
}

void mergeTemporaryValues(){
    xA = tempXA;
    xB = tempXB;
    xM = tempXM;
}

int onTimeSimulate(float timeTarget) {
    if(timeT >= 8.99e6){
        //printf("%d %d %d\n", xA, xM, xB);
    }
    if(timeT >= timeTarget){
        takeMeasures(timeTarget);
        return 0;
    }
    mergeTemporaryValues();
	timeT += 1.0 / 3.0;
	onParticleUpdate(randomIntOf(0, 3));
    return 1;
}

void writeSpecifications(FILE *file){
    int isCompl = file == fCompl;
    fprintf(file, "# Inertial Walls on Random Walk\n");
	fprintf(file, "# Data generated by: L. Possamai\n");
	fprintf(file, "# Seed: %d\n", seed);
	if(SCALE == 0){
		fprintf(file, "# Linear Tics: %d\n", TTICS);
	} else {
		fprintf(file, "# Log Tics: %d\n", TTICS);
	}
	switch(MODE){
	    case 0:
	        fprintf(file, "# dEta: %.5f\n", dEta);
	        fprintf(file, "# t, xA, xB, xM, W\n");
	        break;  
	    case 1:
	    
	        fprintf(file, "# dEta: [%.5f, %.5f]\n", (float) DETAMIN, (float)DETAMAX);
	        if(!isCompl){
	            fprintf(file, "# t dEta W_stat\n"); 
	        } else {
	            fprintf(file, "# Measures: %d\n", (int) LOOPS);
	            fprintf(file, "# dEta <W_stat>\n");
	        }
	        break;
	        
	        
	}
    
}
float timeForDEta(float dEta, int forStat){
    return forStat ? 1.0e1 / (dEta * dEta) : 1.0e1 / dEta;
}

void takeMeasures(float timeTarget){
    if(MODE == 0){
        fprintf(f, "%.2f %d %d %d %d\n", timeTarget, xA, xB, xM, xB - xA);
    } else if(MODE == 1){
        lastMeasure += xB - xA;
        fprintf(f, "%.2f %.5f %d\n", timeTarget, dEta, (xB - xA));
    }
    
}
//0 = A, 1 = M, 2 = B;
void onParticleUpdate(int particle){
    int p;
    switch(particle){
        case 1:
            // decides on which direction the inner particle will walk
            p = (randomFloat() < .5) ? 1 : -1;
            tempXM += p;
            if(tempXM == tempXA || tempXM == tempXB){
                tempXM -= p;
            }
            break;
        case 0:
            if(tempXA + 1 == tempXM){
                tempXA--;
                etaA = 0;
            } else {
                etaA += dEta;
                if(etaA >= 1.0){
                    etaA = 0;
                    tempXA++;    
                }
            }
            break;
        case 2:
            if(tempXB - 1 == tempXM){
                tempXB++;
                etaB = 0;
            } else {
                etaB += dEta;
                if(etaB >= 1.0){
                    etaB = 0;
                    tempXB--;
                }    
            }
            break;
        
    }
    
}








